routes/web.php
<?php

use App\Http\Controllers\Admin\ChartController;
use App\Http\Controllers\Survey\ResearcherSurveyJSWebController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\QuestionBankTemplateController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AssignUserRole;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\SocialAccountController;
use App\Http\Controllers\NewsController as News;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\MidtransController;
use App\Http\Controllers\PickRoleActionController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\Respondent\SurveyController as RespondenSurveyController;
use App\Http\Controllers\Respondent\Validate\ValidationController;
use App\Http\Controllers\Survey\SurveyController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\SubcriptionController;
use App\Http\Controllers\TutorialController;
use App\Http\Controllers\Admin\SurveyController as SurveyInAdmin;
use App\Http\Controllers\Admin\SurveyJSController as SurveyJSInAdmin;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\Respondent\SurveyHistoryController;
use App\Http\Controllers\Respondent\SurveyJSWebController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes(['verify' => true]);
Auth::routes();

// register controller
Route::get('register/{role}', [
    RegisterController::class,
    'showRegistrationForm',
])->name('register.withRole');

Route::get('/form', [App\Http\Controllers\HomeController::class, 'formDemo']);

Route::get('/playground', [
    App\Http\Controllers\HomeController::class,
    'playground',
])->middleware('auth');

/* non-middleware routes */
Route::view('/about', 'about')->name('about');
Route::get('/', [HomeController::class, 'index'])->middleware('redirect')->name('home');
Route::view('/tac', 'tac')->name('tac');
Route::view('/privacy', 'privacy')->name('privacy');

/* News Routes */
Route::prefix('news')
    ->name('news.')->group(function () {
        Route::get('/', [News::class, 'index'])->name('index');
        Route::get('{news:slug}', [News::class, 'show'])->name('show');
    });

Route::get('/contact', [ContactController::class, 'index'])->name('contact.index');
Route::post('/contact', [ContactController::class, 'composeEmail'])->name('contact.compose');
Route::get('pricing', [SubcriptionController::class, 'index'])->name('pricing');
// Route::view('/payment', 'payment')->name('payment');
Route::view('/faq', 'faq.faq')->name('faq');
Route::view('/faq/general-information', 'faq.general-information')->name('general-information');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('user/pick-role', [AssignUserRole::class, 'index'])->name('user.pick-role');
    Route::post('user/pick-role', [AssignUserRole::class, 'assign'])->name('user.store-role');
    Route::get('/profile', [
        App\Http\Controllers\HomeController::class,
        'profile',
    ])->name('user-profile');
    Route::get(
        '/profile/{id}/delete',
        'App\Http\Controllers\UsersProfileController@destroy'
    )->name('user-profile.delete');
});

/* Screening routes */
Route::middleware(['guest'])->group(function () {
    /* screening routes */
    Route::view('/choose-role', 'screening.choose-role')->name('choose-role');
});

Route::get('/respondent/dashboard/filter', [App\Http\Controllers\Respondent\SurveyController::class, 'filter']);

/* Researcher routes */
Route::middleware(['auth', 'role:researcher', 'verified'])->group(function () {
    Route::prefix('researcher')
        ->name('researcher.')
        ->group(function () {
            // Route::view('pricing', 'researcher.pricing'); 
            // Route::view('payment', 'researcher.payment');
            // Route::view('tutorial', 'researcher.tutorial');
            Route::get('tutorial', [TutorialController::class, 'index'])->name('tutorial.index');
            Route::get('tutorial/{news:slug}', [TutorialController::class, 'show'])->name('tutorial.show');

            //survey resource
            Route::prefix('surveys')
                ->name('surveys.')
                ->group(function () {
                    Route::get('/', [
                        SurveyController::class,
                        'showUserSurvey',
                    ])->name('index');
                    Route::get('/{survey}/manage', [
                        SurveyController::class,
                        'surveyManagement',
                    ])->name('manage');
                    Route::get('/{survey}/preview', [
                        SurveyController::class,
                        'showSurveyDetails',
                    ])->name('show');

                    //create survey
                    Route::post('/', [
                        SurveyController::class,
                        'storeSurvey',
                    ])->name('store');

                    

                    //delete survey
                    Route::delete('/{id}', [SurveyController::class, 'destroy'])->name('delete');

                    //update survey Judul & Desc
                    Route::post('/{survey}/manage', [SurveyController::class, 'update'])->name('update');
                    
                    //update survey Logo
                    Route::post('/{survey}/manage/update-logo', [SurveyController::class, 'updateLogo'])->name('updateLogo');

                    //update survey Background Survey
                    Route::post('/{survey}/manage/update-background', [SurveyController::class, 'updateBackground'])->name('updateBackground');

                    //update survey Header Survey
                    Route::post('/{survey}/manage/update-header', [SurveyController::class, 'updateHeader'])->name('updateHeader');

                    //create questions
                    Route::post('/{survey}/questions', [
                        SurveyController::class,
                        'storeQuestions',
                    ])->name('storeQuestions');

                    //create draft questions
                    Route::post('/{survey}/draft-questions', [
                        SurveyController::class,
                        'storeDraftQuestions',
                    ])->name('storeDraftQuestions');

                    // customize diagram
                    Route::get('/{survey}/customize-diagram', [
                        SurveyController::class,
                        'customizeDiagram',
                    ])->name('customizeDiagram');

                    // customize diagram excel
                    Route::get('/{survey}/customize-diagram/export_excel', [
                        SurveyController::class,
                        'export_excel',
                    ])->name('answeExportExcel');

                    // customize diagram pdf
                    Route::get('/{survey}/customize-diagram/export-pdf', [
                        SurveyController::class,
                        'exportPdf',
                    ])->name('exportPdf');

                    // customize diagram 
                    Route::post('/{survey}/customize-diagram/export_pdf', [
                        SurveyController::class,
                        'answeExportPdf',
                    ])->name('answeExportPdf');

                    //create diagram
                    Route::post('/{survey}/customize-diagram', [
                        SurveyController::class,
                        'storeDiagrams',
                    ])->name('storeDiagrams');

                    // collect respondent
                    Route::get('/{survey}/collect-respondent', [
                        SurveyController::class,
                        'collectRespondent',
                    ])->name('collectRespondent');

                    // status survey
                    Route::get('/{survey}/status-survey', [
                        SurveyController::class,
                        'statusSurvey',
                    ])->name('statusSurvey');

                    // show report
                    Route::get('{survey}/report', [
                        SurveyController::class,
                        'showReport',
                    ])->name('report');
                });

            // surveyjs resource
            Route::prefix('surveyjs')
                ->name('surveyjs.')
                ->group(function () {
                    Route::get('/edit/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showSurveyCreator',
                    ])->name('creator');
                    Route::get('/collect-respondent/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showCollectRespondent',
                    ])->name('collectRespondent');
                    Route::get('/status-survey/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showStatusSurvey',
                    ])->name('statusSurvey');
                    Route::get('/link-survey/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showLinkSurvey',
                    ])->name('linkSurvey');
                    Route::get('/report/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showReport',

resources/views/researcher/create-survey.blade.php
@extends('layouts.footer')
@extends('layouts.base')
{{-- @extends('researcher.layouts.breadcrumb') --}}
@extends('researcher.layouts.navbar2')

<link rel="stylesheet" href="{{ asset('css/components/spinner.css') }}">
<link rel="stylesheet" href="{{ asset('css/components/rating.css') }}">
<link rel="stylesheet" href="{{ asset('css/components/scale.css') }}">
{{-- <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet"> --}}
@section('content')
    {{-- Breadcrumb --}}
    <section class="breadcrumb-contact mt-3 ms-5" id="breadcrumb-contact">
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                        <a href="/researcher/surveys" class="link-yellow text-decoration-none"><i
                            class="fas fa-home fa-fw"></i>
                        Beranda</a></li> 
                <li class="breadcrumb-item active">
                    <a href=" {{ route('researcher.surveys.manage', $survey->id) }}"
                        class="link-secondary text-decoration-none"> Survey</a>
                </li>
                <li class="breadcrumb-item">
                    <a href=" {{ route('researcher.surveys.customizeDiagram', $survey->id) }}"
                        class="link-secondary text-decoration-none">Diagram</a>
                </li>
                <li class="breadcrumb-item "><a href=" {{ route('researcher.surveys.collectRespondent', $survey->id) }}"
                        class="link-secondary text-decoration-none">Kumpulkan Responden</a>
                </li>
                </li>
                <li class="breadcrumb-item"><a href=" {{ route('researcher.surveys.statusSurvey', $survey->id) }}"
                        class="link-secondary text-decoration-none">Status Survey</a>
                </li>
                <li class="breadcrumb-item"><a href=" {{ route('researcher.surveys.report', $survey->id) }}"
                        class="link-secondary text-decoration-none">Hasil Analisa</a>
                </li>
            </ol>
        </nav>
    </section>
    <hr class="mb-0">
    {{-- end Breadcrumb --}}
    {{-- Alert for survey archived --}}
    <div class="row">
        <div class="col-md-12">
            @if (session()->has('success'))
            <div class="alert alert-success alert-dismissible show fade">
                {{ session()->get('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            @endif
        </div>
    </div>
    {{-- End Alert --}}

    {{-- @include('researcher.layouts.breadcrumb') --}}
    @include('researcher.modals.custom-components-modal')
    @include('researcher.modals.edit-element-modal')
    @include('researcher.modals.question-bank-modal')
    @include('layouts.alerts.delete-question')
    @include('researcher.layouts.sidebar')
    
    {{-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
    <script src="{{ asset('js/bootstrap-paginator.min.js') }}"></script>
    
    <script type='text/javascript'>
        var options = {
            currentPage: 1,
            totalPages: 10,
             
        }

        $('#questions_container').bootstrapPaginator(options);
    </script> --}}

    <script>
        var url = "{!! $url !!}";
    </script>
    <!-- Latest Sortable -->
    <script src="//SortableJS.github.io/Sortable/Sortable.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        var questions = {!! $survey->questions !!};
    </script>
    <script type="module" src="{{ asset('js/researcher/create-survey.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.0/chart.min.js">
    </script>
    {{-- <script type="module" src="{{ asset('js/charts/preview-chart.js') }}"></script> --}}
@endsection

resources/views/researcher/customize-diagram-test.blade.php
@extends('layouts.footer')
@extends('layouts.base')
{{-- @extends('researcher.layouts.breadcrumb') --}}
@extends('researcher.layouts.navbar2')

@section('content')
    {{-- Breadcrumb --}}
    <section class="breadcrumb-contact mt-3 ms-5" id="breadcrumb-contact">
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                        <a href="/researcher/surveys" class="link-yellow text-decoration-none"><i
                            class="fas fa-home fa-fw"></i>
                        Beranda</a></li>
                <li class="breadcrumb-item">
                    <a href=" {{ route('researcher.surveys.manage', $survey->id) }}"
                        class="link-secondary text-decoration-none"> Survey</a>
                </li>
                <li class="breadcrumb-item active">
                    <a href=" {{ route('researcher.surveys.customizeDiagram', $survey->id) }}"
                        class="link-secondary text-decoration-none">Diagram</a>
                </li>
                <li class="breadcrumb-item"><a href=" {{ route('researcher.surveys.collectRespondent', $survey->id) }}"
                        class="link-secondary text-decoration-none">Kumpulkan Responden</a>
                </li>
                </li>
                <li class="breadcrumb-item"><a href=" {{ route('researcher.surveys.statusSurvey', $survey->id) }}"
                        class="link-secondary text-decoration-none">Status Survey</a>
                </li>
                <li class="breadcrumb-item"><a href=" {{ route('researcher.surveys.report', $survey->id) }}"
                        class="link-secondary text-decoration-none">Hasil Analisis</a>
                </li>
            </ol>
        </nav>
    </section>
    <hr class="mb-0">
    {{-- end Breadcrumb --}}


    {{-- Chart List Modal --}}
    @include('researcher.modals.chart-list-modal')
    {{-- <form action="customize-diagram/export_pdf" method="post" id="formExportChart" enctype="multipart/form-data">
        @csrf
        <input type="hidden" name="dataChart" id="dataChart">
    </form> --}}

    <form action="{{ route('researcher.surveys.storeDiagrams', $survey) }}" method="post" id="form">
        @csrf
        <input type="hidden" name="survey_id" value="{{ $survey->id }}">
        <div class="container mt-3 mb-5">
            {{-- <div class="row">
            <div class="dropdown d-flex justify-content-end py-3">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-download"></i>
                </a> --}}

            {{-- <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <li><a class="dropdown-item" href="customize-diagram/export_excel?id={{$survey->id}}">Excel</a></li>
                    <li><span class="dropdown-item" id="btnChartExport" style="cursor: pointer;">PDF</span></li> --}}
            {{-- <li><a class="dropdown-item" href="#">Something else here</a></li> --}}
            {{-- </ul> --}}
            {{-- </div>
        </div> --}}
            @php
                $i = 0;
            @endphp
            @forelse ($questions as $question)
                <div class="row mb-5">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h6 id="questionType_{{ $question->id }}" class="text-capitalize mb-0">Question Type</h6>
                                        <small id="chartType_{{ $question->id }}">Bar chart</small>
                                    </div>
                                    <div class="d-flex">
                                        <div class="text-center me-2">
                                            <a href="#" id="chartModalTogglerBtn_{{ $question->id }}" type="button" data-bs-toggle="modal"
                                                data-bs-target="#chartListModal" data-question-index="{{ $i }}"
                                                class="btn btn-sm btn-orange mb-0">Change
                                                Chart <br>
                                                <span class="fw-light"><small>all options will be reset</small></span>
                                            </a>
                                        </div>
                                        {{-- <a href="#" class="btn btn-primary">
                                    <span>Export Excel</span>
                                </a> --}}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body" id="chartContainer{{ $question->id }}">
                                <div class="row">
                                    <div class="col">
                                        <div class="d-flex top-0 end-0 justify-content-end" id="exportsContainer{{ $question->id }}">
                                            {{-- <div class="dropdown">
                                                <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="exportsContainerBtn"
                                                    data-bs-toggle="dropdown" aria-expanded="false">
                                                    Export
                                                </button>
                                                <ul class="dropdown-menu" aria-labelledby="exportsContainerBtn">
                                                    <li><button class="dropdown-item fs-6 fw-light" id="asPng">PNG</button></li>
                                                    <li><button class="dropdown-item fs-6 fw-light" id="asJpg">JPG</button></li>
                                                    <li><button class="dropdown-item fs-6 fw-light" id="asSvg">SVG</button></li>
                                                    <li><button class="dropdown-item fs-6 fw-light" id="asPdf">PDF</button></li>
                                                    <li><button class="dropdown-item fs-6 fw-light" id="asCsv">CSV</button></li>
                                                    <li><button class="dropdown-item fs-6 fw-light" id="asExc">EXCEL</button></li>
                                                </ul>
                                            </div> --}}
                                        </div>
                                        <div class="list-chart" id="chart{{ $question->id }}" style="height: 440px; padding-top: 30px;"></div>
                                    </div>
                                </div>
                                <div class="collapse row mt-3" id="chart_{{ $question->id }}_editor">
                                    <label for="" class="form-label">Data Manipulation</label>
                                    <div class="d-flex justify-content-evenly mb-3">
                                        <button type="button" class="list-group-item list-group-item-action">Add</button>
                                        <button type="button" class="list-group-item list-group-item-action ms-2">Item</button>
                                        <button type="button" class="list-group-item list-group-item-action ms-2">Disabled
                                            item</button>
                                    </div>
                                    <label for="" class="form-label">Chart Styling</label>
                                    <div class="col mb-3">
                                        @include('researcher.components.chart-styling-card')
                                    </div>
                                </div>
                                <div class="d-flex justify-content-end mt-3">
                                    <button type="button" class="btn btn-sm btn-outline-orange" data-bs-toggle="collapse"
                                        data-bs-target="#chart_{{ $question->id }}_editor" aria-expanded="false"
                                        aria-controls="chart_{{ $question->id }}_editor">options</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @php
                    $i++;
                @endphp
            @empty
                <h6>Tidak ada pertanyaan</h6>
            @endforelse
            <div class="d-grid my-3">
                <button type="submit" class="btn btn-orange">Simpan</button>
            </div>
        </div>
    </form>

    @include('researcher/scripts/anychart')
    <script src="{{ asset('js/app.js') }}"></script>
    @include('researcher/scripts/devexpress')
    <script>
        var questionsData = {!! $questions !!};
    </script>
    <script src="{{ asset('js/charts/main.js') }}" type="module"></script>
    <script src="{{ asset('js/charts/change-chart-modal.js') }}" type="module"></script>

    {{-- <script>
        var btnChartExport = document.getElementById('btnChartExport');
        var formExportChart = document.getElementById('formExportChart');
        var dataChart = document.getElementById('dataChart');

        btnChartExport.addEventListener('click', function() {
            // var piechart = document.getElementById('piechart');
            // dataChart.value = piechart.innerHTML;

            var data = document.querySelectorAll('#form .list-chart');
            for (let i = 0; i < data.length; i++) {
                dataChart.value += data[i].parentElement.innerHTML + '<br /><br /><br /><br />';
            }

            formExportChart.submit();
        });
    </script> --}}

<!-- for modal survey status -->
@if ($survey->status == 'pending')
    @include('researcher.modals.popup-status-pending')
@elseif ($survey->status == 'reject')
    @include('researcher.modals.popup-status-reject')
@else
    @include('researcher.modals.popup-status-draft')
@endif

<script type="text/javascript">
    $(window).on('load', function() {
        if( "{{ $survey->status }}" !== 'active' ) {
            $('#myModal').modal('show');
        } else {
            $('#myModal').modal('hide');
        }
    });
</script>
<!-- end modal survey status -->

@endsection

resources/views/researcher/payment.blade.php
@extends('layouts.footer')
@extends('researcher.layouts.base')
@extends('researcher.layouts.navbar2')

@section('content')

<div class="container-fluid p-5">
    <h2 class="fw-bold text-center mb-5">{{ $subscription->subscription->name }} Account</h2>
    <form action="{{ route('researcher.transaction.store') }}" method="POST">
        @csrf
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h5 class="fw-semibold mt-5">Rincian Pesanan</h5>
                <hr>
                <div class="row">
                    <div class="col">
                        <p>{{ $categorySubscription->title }}</p>
                    </div>
                    <input type="hidden" name="category_id" value="{{ $categorySubscription->id }}">
                    <div class="col text-end">
                        <h5 class="fw-semibold">Rp{{ number_format($categorySubscription->price, 0, 0,
                            '.') }}</h5>
                    </div>
                    <input type="hidden" name="price" value="{{ $categorySubscription->price }}">
                </div>
                <hr>
                <div class="d-flex justify-content-end">

                    <button type="submit" class="btn btn-orange radius-default w-25 my-3" id="pay-button">Beli</button>
                </div>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/researcher/status-survey.blade.php
@extends('layouts.footer')
@extends('layouts.base')
{{-- @extends('researcher.layouts.breadcrumb') --}}
@extends('researcher.layouts.navbar2')

@section('content')

{{-- Breadcrumb --}}
    <section class="breadcrumb-contact mt-3 ms-5" id="breadcrumb-contact">
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                        <a href="/researcher/surveys" class="link-yellow text-decoration-none"><i
                            class="fas fa-home fa-fw"></i>
                        Beranda</a></li>
                <li class="breadcrumb-item">
                    <a href=" {{ route('researcher.surveys.manage', $survey->id) }}"
                        class="link-secondary text-decoration-none"> Survey</a>
                </li>
                <li class="breadcrumb-item">
                    <a href=" {{ route('researcher.surveys.customizeDiagram', $survey->id) }}"
                        class="link-secondary text-decoration-none">Diagram</a>
                </li>
                <li class="breadcrumb-item"><a href=" {{ route('researcher.surveys.collectRespondent', $survey->id) }}"
                        class="link-secondary text-decoration-none">Kumpulkan Responden</a>
                </li>
                </li>
                <li class="breadcrumb-item active"><a href=" {{ route('researcher.surveys.statusSurvey', $survey->id) }}"
                        class="link-secondary text-decoration-none">Status Survey</a>
                </li>
                <li class="breadcrumb-item"><a href=" {{ route('researcher.surveys.report', $survey->id) }}"
                        class="link-secondary text-decoration-none">Hasil Analisis</a>
                </li>
            </ol>
        </nav>
    </section>
    <hr class="mb-0">
{{-- end Breadcrumb --}}

{{-- Data Respondent --}}
<section class="data-respondent py-5" id="data-respondent" style="margin-bottom: 250px">
    <div class="container">
        <h4>Data Responden</h4>
        <table class="table table-hover">
            <thead class="table-orange text-white">
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Metode</th>
                    <th scope="col">Status</th>
                    <th scope="col" class="text-center">Responden</th>
                    <th scope="col">Tanggal Modifikasi</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr class="share">
                    <td class="sharelink">
                        <i class="fas fa-share-alt fa-fw"></i>
                        <small class="copied">copied</small> 
                    </td>
                    <td>
                        <input type="text" class="text" value="{{ $survey->shareable_link }}" readonly>
                    </td>
                    <td>{{ $survey->status }}</td>
                    <td class="text-center">{{ $survey->attempted }}</td>
                    <td>{{ $survey->updated_at->format('l, d M Y H:i') }}</td>
                    <!-- <td><i class="fas fa-ellipsis-h fa-fw"></i></td> -->
                </tr>
                {{-- <tr>
                    <td><i class="fas fa-user-check fa-fw"></i></td>
                    <td>Target Responden</td>
                    <td>Active</td>
                    <td>0</td>
                    <td>Kamis, 30 September 2021, 8:56 PM</td>
                    <!-- <td><i class="fas fa-ellipsis-h fa-fw"></i></td> -->
                </tr> --}}
            </tbody>
        </table>
    </div>
</section>

{{-- End Data Respondent --}}

<!-- for modal survey status -->
@if ($survey->status == 'pending')
    @include('researcher.modals.popup-status-pending')
@elseif ($survey->status == 'reject')
    @include('researcher.modals.popup-status-reject')
@else
    @include('researcher.modals.popup-status-draft')
@endif

<style>
    .sharelink{
        cursor: pointer;
    }
    .text{
        width:100%;
        border: transparent;
        background:transparent;
    }
    .text:focus{
        padding: 2px;
        outline: red;
        background-color: transparent;
    }
    .copied{
        color: transparent;
        padding:2px;
        font-size:10px;
    }
    .activecopied{
        color: white;
        background: grey;
        padding: 3px;
        border-radius: 5px;
    }
</style>

<script type="text/javascript">
    $(window).on('load', function() {
        if( "{{ $survey->status }}" !== 'active' ) {
            $('#myModal').modal('show');
        } else {
            $('#myModal').modal('hide');
        }
    });


    let copied = document.querySelector(".copied")
    let copytext = document.querySelector(".share");
    copytext.querySelector(".sharelink").addEventListener("click", function(){
        let input = copytext.querySelector("input.text");
        input.select();
        document.execCommand("copy");
        copied.classList.add("activecopied");
        setTimeout(function(){
            copied.classList.remove("activecopied");
        }, 500);
    })
</script>
<!-- end modal survey status -->

@endsection