routes/web.php
<?php

use App\Http\Controllers\Admin\ChartController;
use App\Http\Controllers\Survey\ResearcherSurveyJSWebController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\QuestionBankTemplateController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AssignUserRole;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\SocialAccountController;
use App\Http\Controllers\NewsController as News;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\MidtransController;
use App\Http\Controllers\PickRoleActionController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\Respondent\SurveyController as RespondenSurveyController;
use App\Http\Controllers\Respondent\Validate\ValidationController;
use App\Http\Controllers\Survey\SurveyController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\SubcriptionController;
use App\Http\Controllers\TutorialController;
use App\Http\Controllers\Admin\SurveyController as SurveyInAdmin;
use App\Http\Controllers\Admin\SurveyJSController as SurveyJSInAdmin;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\Respondent\SurveyHistoryController;
use App\Http\Controllers\Respondent\SurveyJSWebController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes(['verify' => true]);
Auth::routes();

// register controller
Route::get('register/{role}', [
    RegisterController::class,
    'showRegistrationForm',
])->name('register.withRole');

Route::get('/form', [App\Http\Controllers\HomeController::class, 'formDemo']);

Route::get('/playground', [
    App\Http\Controllers\HomeController::class,
    'playground',
])->middleware('auth');

/* non-middleware routes */
Route::view('/about', 'about')->name('about');
Route::get('/', [HomeController::class, 'index'])->middleware('redirect')->name('home');
Route::view('/tac', 'tac')->name('tac');
Route::view('/privacy', 'privacy')->name('privacy');

/* News Routes */
Route::prefix('news')
    ->name('news.')->group(function () {
        Route::get('/', [News::class, 'index'])->name('index');
        Route::get('{news:slug}', [News::class, 'show'])->name('show');
    });

Route::get('/contact', [ContactController::class, 'index'])->name('contact.index');
Route::post('/contact', [ContactController::class, 'composeEmail'])->name('contact.compose');
Route::get('pricing', [SubcriptionController::class, 'index'])->name('pricing');
// Route::view('/payment', 'payment')->name('payment');
Route::view('/faq', 'faq.faq')->name('faq');
Route::view('/faq/general-information', 'faq.general-information')->name('general-information');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('user/pick-role', [AssignUserRole::class, 'index'])->name('user.pick-role');
    Route::post('user/pick-role', [AssignUserRole::class, 'assign'])->name('user.store-role');
    Route::get('/profile', [
        App\Http\Controllers\HomeController::class,
        'profile',
    ])->name('user-profile');
    Route::get(
        '/profile/{id}/delete',
        'App\Http\Controllers\UsersProfileController@destroy'
    )->name('user-profile.delete');
});

/* Screening routes */
Route::middleware(['guest'])->group(function () {
    /* screening routes */
    Route::view('/choose-role', 'screening.choose-role')->name('choose-role');
});

Route::get('/respondent/dashboard/filter', [App\Http\Controllers\Respondent\SurveyController::class, 'filter']);

/* Researcher routes */
Route::middleware(['auth', 'role:researcher', 'verified'])->group(function () {
    Route::prefix('researcher')
        ->name('researcher.')
        ->group(function () {
            // Route::view('pricing', 'researcher.pricing'); 
            // Route::view('payment', 'researcher.payment');
            // Route::view('tutorial', 'researcher.tutorial');
            Route::get('tutorial', [TutorialController::class, 'index'])->name('tutorial.index');
            Route::get('tutorial/{news:slug}', [TutorialController::class, 'show'])->name('tutorial.show');

            //survey resource
            Route::prefix('surveys')
                ->name('surveys.')
                ->group(function () {
                    Route::get('/', [
                        SurveyController::class,
                        'showUserSurvey',
                    ])->name('index');
                    Route::get('/{survey}/manage', [
                        SurveyController::class,
                        'surveyManagement',
                    ])->name('manage');
                    Route::get('/{survey}/preview', [
                        SurveyController::class,
                        'showSurveyDetails',
                    ])->name('show');

                    //create survey
                    Route::post('/', [
                        SurveyController::class,
                        'storeSurvey',
                    ])->name('store');

                    

                    //delete survey
                    Route::delete('/{id}', [SurveyController::class, 'destroy'])->name('delete');

                    //update survey Judul & Desc
                    Route::post('/{survey}/manage', [SurveyController::class, 'update'])->name('update');
                    
                    //update survey Logo
                    Route::post('/{survey}/manage/update-logo', [SurveyController::class, 'updateLogo'])->name('updateLogo');

                    //update survey Background Survey
                    Route::post('/{survey}/manage/update-background', [SurveyController::class, 'updateBackground'])->name('updateBackground');

                    //update survey Header Survey
                    Route::post('/{survey}/manage/update-header', [SurveyController::class, 'updateHeader'])->name('updateHeader');

                    //create questions
                    Route::post('/{survey}/questions', [
                        SurveyController::class,
                        'storeQuestions',
                    ])->name('storeQuestions');

                    //create draft questions
                    Route::post('/{survey}/draft-questions', [
                        SurveyController::class,
                        'storeDraftQuestions',
                    ])->name('storeDraftQuestions');

                    // customize diagram
                    Route::get('/{survey}/customize-diagram', [
                        SurveyController::class,
                        'customizeDiagram',
                    ])->name('customizeDiagram');

                    // customize diagram excel
                    Route::get('/{survey}/customize-diagram/export_excel', [
                        SurveyController::class,
                        'export_excel',
                    ])->name('answeExportExcel');

                    // customize diagram pdf
                    Route::get('/{survey}/customize-diagram/export-pdf', [
                        SurveyController::class,
                        'exportPdf',
                    ])->name('exportPdf');

                    // customize diagram 
                    Route::post('/{survey}/customize-diagram/export_pdf', [
                        SurveyController::class,
                        'answeExportPdf',
                    ])->name('answeExportPdf');

                    //create diagram
                    Route::post('/{survey}/customize-diagram', [
                        SurveyController::class,
                        'storeDiagrams',
                    ])->name('storeDiagrams');

                    // collect respondent
                    Route::get('/{survey}/collect-respondent', [
                        SurveyController::class,
                        'collectRespondent',
                    ])->name('collectRespondent');

                    // status survey
                    Route::get('/{survey}/status-survey', [
                        SurveyController::class,
                        'statusSurvey',
                    ])->name('statusSurvey');

                    // show report
                    Route::get('{survey}/report', [
                        SurveyController::class,
                        'showReport',
                    ])->name('report');
                });

            // surveyjs resource
            Route::prefix('surveyjs')
                ->name('surveyjs.')
                ->group(function () {
                    Route::get('/edit/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showSurveyCreator',
                    ])->name('creator');
                    Route::get('/collect-respondent/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showCollectRespondent',
                    ])->name('collectRespondent');
                    Route::get('/status-survey/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showStatusSurvey',
                    ])->name('statusSurvey');
                    Route::get('/link-survey/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showLinkSurvey',
                    ])->name('linkSurvey');
                    Route::get('/report/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showReport',

resources/views/about.blade.php
@extends('layouts.footer')
@extends('layouts.base')
@extends('layouts.navbar')

@section('content')

{{-- Hero About --}}
<section class="hero-about py-5" id="hero-about">
    <div class="container">
        <div class="row h-25">
            <div class="col-auto align-self-center">
                <h1 class="text-white fw-semibold">Tentang Kami</h1>
            </div>
        </div>
    </div>
</section>
{{-- End Hero About --}}

{{-- Vision & Mission --}}
<h3 class="text-center mt-5 fw-bold">Visi & Misi</h3>
<hr class="hr-vm-orange mx-auto">
<section class="vision-mission py-5" id="vision-mission">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h4 class="text-orange fw-bold">Visi</h4>
                <h5 class="text-justify fw-normal">"Menjadi platform riset online pilihan bagi individu maupun
                    perusahaan."</h5>
            </div>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                <h4 class="text-orange fw-bold">Misi</h4>
                <h5 class="text-justify fw-normal">"SurveyAsia membantu individu maupun perusahaan dengan memberikan
                    solusi riset yang cepat dan handaldengan dukungan teknologi 5.0 untuk membantu pengambilan
                    keputusan yang tepat dan berkualitas."</h5>
            </div>
        </div>
</section>
{{-- End Vision & Mission --}}

{{-- Partner --}}
<section class="partner py-5 bg-light" id="partner">
    <div class="container">
        <h3 class="text-center fw-bold">Mitra & Klien</h3>
        <hr class="hr-vm-orange mx-auto">
        <div class="row d-flex align-items-center mt-5">
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/citiasia.png') }}" alt="Citiasia" class="img-fluid" width="300">
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/vocasia.png') }}" alt="Vocasia" class="img-fluid" width="300">
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/midtrans.png') }}" alt="Midtrans" class="img-fluid" width="300">
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/infobank.png') }}" alt="Infobank" class="img-fluid" width="500">
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/pertamina.png') }}" alt="Pertamina" class="img-fluid" width="500">
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/bpom.png') }}" alt="Badan POM" class="img-fluid" width="500">
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/pegadaian.png') }}" alt="Pegadaian" class="img-fluid" width="500">
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/bank_bjb.png') }}" alt="Bank BJB" class="img-fluid" width="500">
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mt-5">
                <img src="{{ asset('assets/img/trans_7.png') }}" alt="Trans 7" class="img-fluid" width="500">
            </div>
        </div>
    </div>
</section>
{{-- End Partner --}}

{{-- Contanct Info --}}
<section class="contact-info py-5" id="contact-info">
    <div class="container">
        <h3 class="fw-bold">Informasi Kontak</h3>
        <hr class="hr-vm-orange">
        <h5 class="text-secondary">Butuh pertolongan?</h5>
        <p class="text-secondary">Berikut cara menghubungi kami.</p>
        <a href="{{ route('contact.index') }}" class="link-orange fs-5 fw-bold">Kirim permintaan bantuan <i
                class="fas fa-long-arrow-alt-right"></i></a>
        <div class="row mt-4">
            <div class="col-lg-3 d-flex">
                <img src="{{ asset('assets/img/ic_contact_info_1.png') }}" alt="Address" class="me-3" width="36"
                    height="36">
                <p class="">Graha Mustika Ratu 5th Floor 503, Tebet, Jakarta Selatan 12870</p>
            </div>
            <div class="col-lg-3 d-flex">
                <img src="{{ asset('assets/img/ic_contact_info_2.png') }}" alt="Telp" class="me-3" width="36"
                    height="36">
                <p class="">021-8370-7143</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 d-flex">
                <img src="{{ asset('assets/img/ic_contact_info_3.png') }}" alt="Email" class="me-3" width="36"
                    height="36">
                <p class="">support@surveyasia.id</p>
            </div>
            <div class="col-lg-3 d-flex">
                <img src="{{ asset('assets/img/ic_contact_info_4.png') }}" alt="Telp" class="me-3" width="36"
                    height="36">
                <p class="">021-8370-5680</p>
            </div>
        </div>
    </div>
</section>
{{-- End Contact Info --}}

@endsection

resources/views/authvue.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Surveyasia</title>
  </head>
  <body>
    <div id="app">
      <auth />
    </div>
  
    <script src="{{ mix('/js/app.js') }}"></script>
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>

resources/views/pdf-tmp.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>PDF-Export</title>
</head>
<body>
    @if ($data)
        {!! $data !!}
    @endif
</body>
</html>

resources/views/profile.blade.php
@extends('layouts.footer')
@extends('layouts.base')

@if (Auth::user()->role_id == 2)
@include('researcher.layouts.navbar2')
@elseif(Auth::user()->role_id == 3)
@include('respondent.layouts.navbar2')
@endif

@section('content')

<h3 class="pt-5 ms-5 fw-bold">Akun Saya</h3>

{{-- User Dashboard --}}
<section class="user-profile pt-4 pb-5 mx-5" id="user-profile">
    <div class="row">
        {{-- Sidebar --}}
        <div class="col-lg-2 d-none d-md-block">
            <div class="shadow p-4 me-4" style="border-radius: 16px;">
                <h5>Personal</h5>
                <a href="{{ route('user-profile') }}" class="link-dark text-decoration-none">
                    <p class="mt-3 ms-3"><i class="fas fa-user fa-fw"></i> profil</p>
                </a>
                @if(Auth::user()->role_id == 3)
                <a href="{{ route('respondent.survey.history') }}" class="link-dark text-decoration-none">
                    <p class="mt-3 ms-3"><i class="fas fa-ticket-alt fa-fw"></i> Saldo Hadiah</p>
                </a>
                @endif
                @if (Auth::user()->role_id == 2)
                <a href="{{ route('researcher.transaction.history') }}" class="link-dark text-decoration-none">
                    <p class="mt-3 ms-3"><i class="fas fa-file-invoice-dollar fa-fw"></i> Riwayat Transaksi</p>
                </a>
                <a href="{{ route('researcher.tutorial.index') }}" class="link-dark text-decoration-none">
                    <p class="mt-3 ms-3"><i class="fas fa-tv fa-fw"></i> Tutorial</p>
                </a>
                @endif
                <a href="{{ route('news.index') }}" class="link-dark text-decoration-none">
                    <p class="mt-3 ms-3"><i class="fas fa-newspaper fa-fw"></i> Berita</p>
                </a>
                <a href="{{ route('contact.index') }}" class="link-dark text-decoration-none">
                    <p class="mt-3 ms-3"><i class="fas fa-phone-alt fa-fw"></i> Kontak</p>
                </a>
                <form action="{{ route('logout') }}" method="POST" class="m-0">
                    @csrf
                    <button type="submit" class="dropdown-item"><i class="fas fa-sign-out-alt fa-fw"></i>
                        Keluar</button>
                </form>
            </div>
        </div>
        {{-- End Sidebar --}}

        {{-- User Profile --}}
        <div class="col-lg-10 shadow pt-4 pb-5 px-5" style="border-radius: 16px;">
            @if (session('success'))
            <div class="alert alert-success alert-dismissible show fade">
                {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            @endif
            @if (session('error'))
            <div class="alert alert-danger alert-dismissible show fade">
                {{ session('error') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            @endif
            <div class="row">
                <div class="col-md-2">
                    @if (Auth::user()->avatar == null)
                    <img src="{{ asset('assets/img/noimage.png') }}" alt="Profile Picture" width="110"
                        class="img-fluid d-block mb-2 ms-3 rounded-pill object-fit-cover">
                    @elseif (Auth::user()->provider_name != null)
                    <img src="{{ Auth::user()->avatar }}" alt="{{ Auth::user()->nama_lengkap }}" width="110"
                        class="img-fluid d-block mb-2 ms-3 rounded-pill object-fit-cover">
                    @else
                    <img src="{{ asset('storage/' . \Auth::user()->avatar) }}" width="110" height="110"
                        alt="{{ Auth::user()->nama_lengkap }}"
                        class="img-fluid d-block mb-2 ms-3 rounded-pill object-fit-cover" name="avatar">
                    @endif
                    <span class="d-flex">
                        <a href="{{ route('edit-profile') }}" class="link-orange text-decoration-none">Change</a>
                        <p class="text-orange m-0 mx-1">|</p>
                        <a href="{{ route('user-profile.delete', [\Auth::user()->id]) }}" method="post"
                            class="link-orange text-decoration-none"
                            onclick="return confirm('Apakah Anda yakin menghapus Foto Profil ini?')">Delete</a>
                        @csrf
                        @method('DELETE')
                    </span>
                </div>
                <div class="col">
                    <h3 class="fw-semibold">{{ $user->nama_lengkap }}</h3>
                    @if ($userSubsId->category_id == 1)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-3"> {{
                        $subscription[0]->title }} Account</p>
                    <br>
                    <a href="{{ route('pricing') }}" class="btn btn-orange btn-sm radius-default"
                        role="button">Upgrade</a>
                    @elseif($userSubsId->category_id == 2)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> Pay Per Survey
                        Account
                    </p>
                    @elseif ($userSubsId->category_id == 3)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> Pay Per Survey
                        Account
                    </p>
                    @elseif ($userSubsId->category_id == 4)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> {{
                        $subscription[3]->title }} Account</p>
                    @elseif ($userSubsId->category_id == 5)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> {{
                        $subscription[4]->title }} Account</p>
                    @elseif ($userSubsId->category_id == 6)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> {{
                        $subscription[5]->title }} Account</p>
                    @elseif ($userSubsId->category_id == 7)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> {{
                        $subscription[6]->title }} Account</p>
                    @elseif ($userSubsId->category_id == 8)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> {{
                        $subscription[7]->title }} Account</p>
                    @elseif ($userSubsId->category_id == 9)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> {{
                        $subscription[8]->title }} Account</p>
                    @elseif ($userSubsId->category_id == 10)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> {{
                        $subscription[9]->title }} Account</p>
                    @elseif ($userSubsId->category_id == 11)
                    <p class="text-dark fw-normal badge bg-warning rounded-pill text-white mb-1"> {{
                        $subscription[10]->title }} Account</p>
                    @else
                    <p class="text-white fw-normal badge bg-dark rounded-pill mb-1"> {{ $subscription->title
                        }}Account</p>
                    @endif
                    @if ($userSubsId->category_id > 1)
                    <p class="text-muted fs-12px">Paket akan berakhir pada {{ date('j F Y',
                        strtotime($userSubsId->expired_at)) }}</p>
                    @endif
                </div>
            </div>
            <div class="d-flex justify-content-end mt-3">
                <a href="{{ route('edit-profile') }}" class="btn btn-outline-orange radius-default">Edit Profil</a>
            </div>

            <div class="row mt-4">
                <div class="col-md-2">
                    <p>Nama</p>
                </div>
                <div class="col">
                    <p class="fw-semibold">{{ $user->nama_lengkap }}</p>
                </div>
                <hr>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <p>Email</p>
                </div>
                <div class="col">
                    <p class="fw-semibold">{{ Auth::user()->email }}</p>
                    <div class="d-flex">
                        @if (Auth::user()->email_verified_at != null)
                        <p class="text-success me-3">Verified</p>
                        @else
                        <p class="text-orange me-3">Not Verified</p>
                        <a href="#" class="link-orange text-decoration-none">Resend
                            Email</a>
                        @endif
                    </div>
                </div>
                <hr>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <p>No. Telepon</p>
                </div>
                <div class="col">
                    <p class="fw-semibold">{{ $user->profile->telp ?? $user->telp }}</p>
                </div>
                <hr>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <p>Pekerjaan</p>
                </div>
                <div class="col">
                    <p class="fw-semibold">{{ $user->profile->job ?? $user->job }}</p>
                </div>
                <hr>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <p>Alamat</p>
                </div>
                <div class="col">
                    <p class="fw-semibold">
                        {{ $user->profile->address ?? $user->address }}
                    </p>
                </div>
                <hr>
            </div>
        </div>
    </div>
</section>
{{-- End User Profile --}}

@endsection

resources/views/surveypemilu.blade.php
<!doctype html>
<html lang="en">

<head>
  <title>Pemilu SurveyAsia</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {{-- Favicon --}}
  <link rel='icon' type='image/jpg' href='/favicon_surveyasia-32.png' />
  <link rel='shortcut icon' type='image/x-icon' href='/favicon-surveyasia-32.ico' />

  <!-- Bootstrap CSS v5.2.0-beta1 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

</head>

<body>
  <header>
    <center>
      <img class="img-fluid mb-2 mt-2" src="/assets/img/surveyasia_black.png" alt="" style="max-width: 200px"/>
    </center>
    <!-- place navbar here -->
  </header>

  <div id="app">
    <pemilu></pemilu>
 </div>

  <script src="{{ mix('/js/app.js') }}"></script>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
    integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous">
  </script>
</body>

</html>

resources/views/table list user from ifan.blade.php
table list user from ifan 
<table class="table table-no-border-head align-middle">
              <thead>
                  <tr>
                      <td scope="col"></td>
                      <td scope="col">Nama</td>
                      <td scope="col">Email</td>
                      <td scope="col">Role</td>
                      <td scope="col">Subscription</td>
                      <td scope="col">Actions</td>
                  </tr>
              </thead>
              <tbody>
                @foreach ($users as $user)
                  @if ($user->role_id == 1)
                    @php
                      continue;
                    @endphp
                  @endif
                  <tr>
                    @if ($user->profile != null)
                      <td scope="col" class="d-flex align-items-center">
                          {{-- <img src="{{ asset('assets/img/photo-neil-seims.jpg') }}" alt="" class="rounded-pill me-2"> --}}
                          <div>
                              <a href="{{ route('admin.users.profile', $user->id) }}">
                                <h6 class="nopadding">{{ $user->first_name }}
                                  {{ $user->last_name }}</h6>
                              </a>
                              <span class="d-block" style="font-size: 13px">{{ $user->email }}</span>
                          </div>
                      </td>
                      @else
                      {{-- <img src="{{ asset('assets/img/photo-neil-seims.jpg') }}" alt="" class="rounded-pill me-2"> --}}
                          <div>
                                <h6 class="nopadding">{{ $user->first_name }}{{ $user->last_name }}</h6>
                              <span class="d-block" style="font-size: 13px">{{ $user->email }}</span>
                          </div>
                    @endif
                      <td>{{ $user->username }}</td>
                      @if ($user->role_id != null && $user->role != null)
                        <td>{{ $user->role->name }}</td>
                      @else
                        <td>No Role Selected</td>
                      @endif
                      @if ($user->subscription_id != null && $user->subscription != null)
                        <td>{{ $user->subscription->name }}</td>
                      @else
                        <td>{{ __('No Subscription') }}</td>
                      @endif
                     
                      <td class="text-end">
                        <button type="button" class="btn bg-special-blue text-white">
                          <i class="bi bi-vector-pen me-"></i>  
                          Edit Item
                        </button>
                      </td>
                      </tr>
                    @endforeach
              </tbody>
</table>