routes/web.php
<?php

use App\Http\Controllers\Admin\ChartController;
use App\Http\Controllers\Survey\ResearcherSurveyJSWebController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\QuestionBankTemplateController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AssignUserRole;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\SocialAccountController;
use App\Http\Controllers\NewsController as News;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\MidtransController;
use App\Http\Controllers\PickRoleActionController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\Respondent\SurveyController as RespondenSurveyController;
use App\Http\Controllers\Respondent\Validate\ValidationController;
use App\Http\Controllers\Survey\SurveyController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\SubcriptionController;
use App\Http\Controllers\TutorialController;
use App\Http\Controllers\Admin\SurveyController as SurveyInAdmin;
use App\Http\Controllers\Admin\SurveyJSController as SurveyJSInAdmin;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\Respondent\SurveyHistoryController;
use App\Http\Controllers\Respondent\SurveyJSWebController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes(['verify' => true]);
Auth::routes();

// register controller
Route::get('register/{role}', [
    RegisterController::class,
    'showRegistrationForm',
])->name('register.withRole');

Route::get('/form', [App\Http\Controllers\HomeController::class, 'formDemo']);

Route::get('/playground', [
    App\Http\Controllers\HomeController::class,
    'playground',
])->middleware('auth');

/* non-middleware routes */
Route::view('/about', 'about')->name('about');
Route::get('/', [HomeController::class, 'index'])->middleware('redirect')->name('home');
Route::view('/tac', 'tac')->name('tac');
Route::view('/privacy', 'privacy')->name('privacy');

/* News Routes */
Route::prefix('news')
    ->name('news.')->group(function () {
        Route::get('/', [News::class, 'index'])->name('index');
        Route::get('{news:slug}', [News::class, 'show'])->name('show');
    });

Route::get('/contact', [ContactController::class, 'index'])->name('contact.index');
Route::post('/contact', [ContactController::class, 'composeEmail'])->name('contact.compose');
Route::get('pricing', [SubcriptionController::class, 'index'])->name('pricing');
// Route::view('/payment', 'payment')->name('payment');
Route::view('/faq', 'faq.faq')->name('faq');
Route::view('/faq/general-information', 'faq.general-information')->name('general-information');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('user/pick-role', [AssignUserRole::class, 'index'])->name('user.pick-role');
    Route::post('user/pick-role', [AssignUserRole::class, 'assign'])->name('user.store-role');
    Route::get('/profile', [
        App\Http\Controllers\HomeController::class,
        'profile',
    ])->name('user-profile');
    Route::get(
        '/profile/{id}/delete',
        'App\Http\Controllers\UsersProfileController@destroy'
    )->name('user-profile.delete');
});

/* Screening routes */
Route::middleware(['guest'])->group(function () {
    /* screening routes */
    Route::view('/choose-role', 'screening.choose-role')->name('choose-role');
});

Route::get('/respondent/dashboard/filter', [App\Http\Controllers\Respondent\SurveyController::class, 'filter']);

/* Researcher routes */
Route::middleware(['auth', 'role:researcher', 'verified'])->group(function () {
    Route::prefix('researcher')
        ->name('researcher.')
        ->group(function () {
            // Route::view('pricing', 'researcher.pricing'); 
            // Route::view('payment', 'researcher.payment');
            // Route::view('tutorial', 'researcher.tutorial');
            Route::get('tutorial', [TutorialController::class, 'index'])->name('tutorial.index');
            Route::get('tutorial/{news:slug}', [TutorialController::class, 'show'])->name('tutorial.show');

            //survey resource
            Route::prefix('surveys')
                ->name('surveys.')
                ->group(function () {
                    Route::get('/', [
                        SurveyController::class,
                        'showUserSurvey',
                    ])->name('index');
                    Route::get('/{survey}/manage', [
                        SurveyController::class,
                        'surveyManagement',
                    ])->name('manage');
                    Route::get('/{survey}/preview', [
                        SurveyController::class,
                        'showSurveyDetails',
                    ])->name('show');

                    //create survey
                    Route::post('/', [
                        SurveyController::class,
                        'storeSurvey',
                    ])->name('store');

                    

                    //delete survey
                    Route::delete('/{id}', [SurveyController::class, 'destroy'])->name('delete');

                    //update survey Judul & Desc
                    Route::post('/{survey}/manage', [SurveyController::class, 'update'])->name('update');
                    
                    //update survey Logo
                    Route::post('/{survey}/manage/update-logo', [SurveyController::class, 'updateLogo'])->name('updateLogo');

                    //update survey Background Survey
                    Route::post('/{survey}/manage/update-background', [SurveyController::class, 'updateBackground'])->name('updateBackground');

                    //update survey Header Survey
                    Route::post('/{survey}/manage/update-header', [SurveyController::class, 'updateHeader'])->name('updateHeader');

                    //create questions
                    Route::post('/{survey}/questions', [
                        SurveyController::class,
                        'storeQuestions',
                    ])->name('storeQuestions');

                    //create draft questions
                    Route::post('/{survey}/draft-questions', [
                        SurveyController::class,
                        'storeDraftQuestions',
                    ])->name('storeDraftQuestions');

                    // customize diagram
                    Route::get('/{survey}/customize-diagram', [
                        SurveyController::class,
                        'customizeDiagram',
                    ])->name('customizeDiagram');

                    // customize diagram excel
                    Route::get('/{survey}/customize-diagram/export_excel', [
                        SurveyController::class,
                        'export_excel',
                    ])->name('answeExportExcel');

                    // customize diagram pdf
                    Route::get('/{survey}/customize-diagram/export-pdf', [
                        SurveyController::class,
                        'exportPdf',
                    ])->name('exportPdf');

                    // customize diagram 
                    Route::post('/{survey}/customize-diagram/export_pdf', [
                        SurveyController::class,
                        'answeExportPdf',
                    ])->name('answeExportPdf');

                    //create diagram
                    Route::post('/{survey}/customize-diagram', [
                        SurveyController::class,
                        'storeDiagrams',
                    ])->name('storeDiagrams');

                    // collect respondent
                    Route::get('/{survey}/collect-respondent', [
                        SurveyController::class,
                        'collectRespondent',
                    ])->name('collectRespondent');

                    // status survey
                    Route::get('/{survey}/status-survey', [
                        SurveyController::class,
                        'statusSurvey',
                    ])->name('statusSurvey');

                    // show report
                    Route::get('{survey}/report', [
                        SurveyController::class,
                        'showReport',
                    ])->name('report');
                });

            // surveyjs resource
            Route::prefix('surveyjs')
                ->name('surveyjs.')
                ->group(function () {
                    Route::get('/edit/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showSurveyCreator',
                    ])->name('creator');
                    Route::get('/collect-respondent/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showCollectRespondent',
                    ])->name('collectRespondent');
                    Route::get('/status-survey/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showStatusSurvey',
                    ])->name('statusSurvey');
                    Route::get('/link-survey/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showLinkSurvey',
                    ])->name('linkSurvey');
                    Route::get('/report/{id}', [
                        ResearcherSurveyJSWebController::class,
                        'showReport',

resources/views/researcher/modals/chart-list-modal.blade.php
<!-- Modal -->
<div class="modal fade" id="chartListModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Daftar diagram</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-fluid" id="chartListContainer">
                    @forelse ($charts as $chart)
                        <div class="row mb-3">
                            <div class="col">
                                <h5>{{ $chart['library_name'] }}</h5>
                                <div class="row">
                                    @forelse ($chart['chart_list'] as $item)
                                        <div class="col-3">
                                            <div class="card" id="lineChart">
                                                <div class="card-body">
                                                    <img class="card-img-top" src="{{ $item['image'] == null ? asset('assets/img/prototyping.png') : url('storage/'. $item['image']) }}" alt="Coming Soon">
                                                    <h6 class="card-title">{{ $item['name'] }}</h6>
                                                    <p class="card-text" style="height: 15rem; max-height:15rem;">
                                                        {{ $item['description'] }}
                                                    </p>
                                                    <div class="d-flex justify-content-end">
                                                        <button type="button" data-chart-code="{{ $item['code'] }}"
                                                            class="btn btn-sm btn-primary">Apply</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @empty
                                        No chart available
                                    @endforelse
                                </div>
                            </div>
                        </div>
                    @empty
                        No chart available
                    @endforelse
                </div>
            </div>
            <div class="modal-footer d-flex justify-content-between">
                <div id="errorMsg" class="alert alert-md alert-danger fade" role="alert">
                    Chart isn't available at this moment
                </div>
                <button type="button" class="btn btn-md btn-secondary" data-bs-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>

resources/views/researcher/modals/create-survey-modal.blade.php
<!-- Modal Create Survey -->
<div class="modal fade" id="addSurveyModal" tabindex="-1" aria-labelledby="addSurveyModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-fullscreen-lg-down modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addSurveyModalLabel">Quickpoll Baru</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ route('researcher.surveys.store') }}" method="POST" class="row g-3 needs-validation">
          @csrf
          <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
          <div class="mb-3">
            <label for="title" class="form-label">Judul</label>
            <input type="text" class="form-control" name="title" id="title" required>
            <div class="invalid-feedback">Harap masukkan <span class="fw-bold">Judul</span> survey!</div>
          </div>
          <div class="mb-3">
            <label for="desc" class="form-label">Deskripsi</label>
            <textarea class="form-control" name="description" id="description" rows="3" required></textarea>
            <div class="invalid-feedback">Harap masukkan <span class="fw-bold">Deskripsi</span> survey!</div>
          </div>
          <div class="mb-3">
            <label for="title" class="form-label">Kategori Survey</label>
            <select name="category_id" id="category_id" class="form-select" required>
              <option value="" selected>Pilih Category</option>
              @foreach ($categories as $category)
              <option value="{{ $category->id }}">{{ $category->name }}</option>
              @endforeach
            </select>
            <div class="invalid-feedback">Harap pilih <span class="fw-bold">Kategori</span> survey!</div>
          </div>
          <div class="mb-3">
            <div class="row">
              <div class="col-md-4">
                <label for="" class="form-label" data-bs-toggle="tooltip" data-bs-placement="top"
                  title="Untuk membantu responden mengetahui berapa lama waktu yang diperlukan untuk menyelesaikan survey ini">Estimasi
                  Penyelesaian
                  {{-- <i class="fa fa-question-circle" aria-hidden="true"></i></label> --}}
                <input type="number" class="form-control" required max="20" min="1" placeholder="dalam satuan menit"
                  name="estimate_completion">
                <div class="form-text"><span class="text-orange">Tips!</span> Disarankan
                  tidak melebihi 10 menit</div>
                <div class="invalid-feedback">Harap masukkan <span class="fw-bold">Estimasi Penyelesaian</span> survey!
                </div>
              </div>
              <div class="col-md-4 mt-3 mt-md-0">
                <label for="" class="form-label">Maksimum Responden
                  {{-- <span><i class="fa fa-question-circle" aria-hidden="true"></i></span></label> --}}
                <input name="max_attempt" type="number" class="form-control" min="1" placeholder="40"
                  @if($user->subscription != null && $user->subscription->id == 1) max="40" @endif>
                @if ($user->subscription != null && $user->subscription->id == 1)
                <div class="form-text">Maksimal 40 respondent untuk
                  <span class="fw-bold">FREE PACKAGE</span>
                </div>
                <div class="invalid-feedback">Jumlah <span class="fw-bold">Maksimum Responden</span> tidak valid!</div>
                @else
                <div class="form-text">Harap isi atau sistem akan menentukan 40 sebagai bawaan</div>
                @endif
              </div>
              <div class="col-md-4 mt-3 mt-md-0">
                <label for="" class="form-label">Jumlah Reward
                  {{-- <span><i class="fa fa-question-circle" aria-hidden="true"></i></span></label> --}}
                <input name="reward_point" type="number" class="form-control" placeholder="0">
              </div>
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label">Pengaturan Survey</label>
            <div class="row">
              <div class="col">
                <div class="form-check form-check-inline">
                  <label class="form-check-label">
                    <input class="form-check-input form-check-input-orange" type="checkbox" name="shareable"
                      value="checkedValue" checked>
                    Survey ini dapat dibagikan
                    {{-- <i class="fa fa-question-circle" aria-hidden="true"></i> --}}
                  </label>
                </div>
              </div>
            </div>
          </div>
          <div class="mb-3">
            <div class="row d-flex justify-content-end">
              <div class="col-auto">
                <button type="button" class="btn btn-outline-orange" data-bs-dismiss="modal">Batal</button>
                <button class="btn btn-orange" type="submit">Simpan</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/researcher/modals/delete-survey-modal.blade.php
<!-- Modal Delete Survey-->
<div class="modal fade" id="deleteSurveyModal{{ $survey->id }}" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center text-center">
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col py-3">
                                <img src="{{ asset('assets/img/Danger-Circle.png') }}" alt="Icon Danger"
                                    class="img-fluid" width="160">
                            </div>
                        </div>
                        <div class="row">
                            <p class="text-delete">Hapus Survey</p>
                            <p class="text-desc-delete">Survey ini akan dihapus secara permanen dari daftar survey Anda <br> dan tidak dapat dikembalikan lagi. Apakah Anda yakin ingin <br> menghapus survey ini?</p>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col py-3">
                                <form action="{{ route('researcher.surveys.delete', $survey->id) }}" method="post">
                                    <button type="button" class="btn btn-gray me-2"
                                        data-bs-dismiss="modal">Batal</button>


                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-save">Ya</button>

                                </form>

                                {{-- <a href="{{ route('researcher.surveys.delete', $survey->id) }}">
                                    <button type="button" class="btn btn-orange">Ya</button>
                                </a> --}}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

resources/views/researcher/modals/delete-surveyjs-modal.blade.php
<!-- Modal Delete Survey-->
<div class="modal fade" id="deleteSurveyJSModal{{ $survey->surveyjs_id }}" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center text-center">
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col py-3">
                                <img src="{{ asset('assets/img/Danger-Circle.png') }}" alt="Icon Danger"
                                    class="img-fluid" width="160">
                            </div>
                        </div>
                        <div class="row">
                            <p class="text-delete">Hapus Survey</p>
                            <p class="text-desc-delete">Survey ini akan dihapus secara permanen dari daftar survey Anda <br> dan tidak dapat dikembalikan lagi. Apakah Anda yakin ingin <br> menghapus survey ini?</p>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col py-3">
                                <form action="{{ route('researcher.surveyjs.delete', $survey->surveyjs_id) }}" method="post">
                                    <button type="button" class="btn btn-gray me-2"
                                        data-bs-dismiss="modal">Batal</button>

                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-save">Ya</button>

                                </form>

                                {{-- <a href="{{ route('researcher.surveys.delete', $survey->id) }}">
                                    <button type="button" class="btn btn-orange">Ya</button>
                                </a> --}}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

resources/views/researcher/modals/edit-judul-deskripsi-modal.blade.php
<div class="modal fade" id="editJudulModal" aria-labelledby="editJudulModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-fullscreen-xl-down modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editJudulLabel">Edit Umum</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{ route('researcher.surveys.update', $survey->id) }}" method="POST">
                    @csrf
                    <div class="row mb-3">
                        <div class="col">
                            <div class="card">
                                <div class="card-body">
                                    <div class="container">
                                        <input type="text" name="title" class="form-control border-0"
                                            value="{{ $survey->title }}"
                                            style="color: #00000099; font-size:24px;"></input>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <div class="card mb-3">
                                <div class="container mt-4">
                                    <label for="" style="font-size:18px; color: #00000099;">Deskripsi</label>
                                    <div class="mb-3 mt-3">
                                        <textarea class="my-editor form-control" id="my-editor" rows="10"
                                            name="description" value="{{ $survey->description }}">{{ $survey->description  }}</textarea>
                                        <!-- <textarea type="text" name="description" value="{{ $survey->description }}"
                                            class="form-control"
                                            style="width: 100%; height:111px;"> {{ $survey->description }}</textarea> -->
                                    </div>
                                </div>

                            </div>
                            <div class="card">
                                <div class="container mt-4">
                                    <label for="" style="font-size:18px; color: #00000099;">Pesan Penutup</label>
                                    <div class="mb-3 mt-3">
                                        <!-- <textarea type="text" name="closing" value="{{ $survey->closing }}"
                                            class="form-control"
                                            style="width: 100%; height:111px;"> {{ $survey->closing }}</textarea> -->
                                            <textarea class="my-editor1 form-control" id="my-editor1" rows="10"
                                            name="closing" value="{{ $survey->closing }}">{{ $survey->closing  }}</textarea>
                                    </div>
                                </div>

                            </div>
                            <div class="text-end mt-3">
                                <button type="button" class="btn btn-gray me-2" data-bs-dismiss="modal">
                                    Batal
                                </button>
                                <button type="submit" class="btn btn-save ms-auto">
                                    Simpan
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/researcher/modals/popup-status-draft.blade.php
<style>
    .btn-modal {
        color: #ef4c29;
        background-color: #F2F2F2;
        border: solid #ef4c29 1px;
    }

    .btn-modal:hover {
      background-color: #ef4c29;
      color: #F2F2F2;
    }

    .color-modal {
        color: #ef4c29;
    }
</style>

<!-- Modal Tolak -->
<div class="modal hide fade in" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body pt-5 pb-4">
                <div class="text-center">
                    <img src="{{ asset('assets/img/survey_draft.svg') }}" width="100px" alt="">
                    <p class="pt-3" style="font-size: 1.2em;">
                        <b>Survey Diarsipkan</b>
                    </p>
                    <p>
                        Saat ini survey <span class="fw-bold">{{ $survey->title }}</span> sedang diarsipkan. Silahkan ajukan 
                        survey dan tunggu persetujuan dari tim kami untuk dapat mengakses dan membagikan tautan.
                    </p>
                </div>
            </div>
            <div class="text-center pb-4">
                <a href="/researcher/surveys" class="btn btn-modal py-2 px-3">Kembali ke Beranda</a>
                <a href="{{ route('researcher.surveys.manage', $survey->id) }}" class="btn btn-modal py-2 px-3">Edit Survey</a>
            </div>
        </div>
    </div>
</div>
<!-- Modal Tolak Akhir -->

resources/views/researcher/modals/popup-status-reject.blade.php
<style>
    .btn-modal {
        color: #ef4c29;
        background-color: #F2F2F2;
        border: solid #ef4c29 1px;
    }

    .btn-modal:hover {
      background-color: #ef4c29;
      color: #F2F2F2;
    }

    .color-modal {
        color: #ef4c29;
    }
</style>

<!-- Modal Tolak -->
<div class="modal hide fade in" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body pt-5 pb-4">
                <div class="text-center">
                    <img src="{{ asset('assets/img/survey ditolak.svg') }}" width="100px" alt="">
                    <p class="pt-3" style="font-size: 1.2em;">
                        <b>Survey Ditolak</b>
                    </p>
                    <p>
                        Maaf, survey <span class="fw-bold">{{ $survey->title }}</span> ditolak karena melanggar aturan kami yaitu
                        <span class="fw-bold">{{ $survey->reason_deny }}</span> Anda dapat mengedit kembali survey Anda dan
                        menunggu persetujuan dari tim kami.
                    </p>
                </div>
            </div>
            <div class="text-center pb-4">
                <a href="/researcher/surveys" class="btn btn-modal py-2 px-3">Kembali ke Beranda</a>
                <a href="{{ route('researcher.surveys.manage', $survey->id) }}" class="btn btn-modal py-2 px-3">Edit Survey</a>
            </div>
        </div>
    </div>
</div>
<!-- Modal Tolak Akhir -->

resources/views/researcher/modals/tinjau-survey-modal.blade.php
<!-- Modal Survey Sedang Di Tinjau-->
<div class="modal fade" id="tinjauSurveyModal" role="dialog">
    <div class="modal-dialog modal-lg modal-dialog-centered">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center text-center">
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col py-3">
                                <img src="{{ asset('assets/img/Danger-Circle.png') }}" alt="Icon Danger"
                                    class="img-fluid" width="160">
                                    <i class="far fa-file-search"></i>
                            </div>
                        </div>
                        <div class="row">
                            <p class="fs-36px fw-bold">Survey Anda sedang ditinjau oleh tim kami hingga 1-2 hari kedepan</p>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col py-3">
                                <a href="{{ route('researcher.dashboard') }}" class="btn btn-orange">Kembali ke Beranda</a>

                                {{-- <a href="{{ route('researcher.surveys.delete', $survey->id) }}">
                                    <button type="button" class="btn btn-orange">Ya</button>
                                </a> --}}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>